name: Publish

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  avoid_redundancy:
    name: avoid redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  lint:
    name: lint project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Lint
        run: npm run lint

  test:
    name: test project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Test
        run: npm run test

  update_version:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    name: update lib version
    runs-on: ubuntu-22.04
    needs:
      - lint
      - test
    permissions:
      contents: write #Allows to publish a GH release
      issues: write #Allows to comment on released issues
      pull-requests: write #Allows to comment on released PRs
      id-token: write # enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Exec semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release

  publish:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'workflow_dispatch'}}
    needs:
      - update_version
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Make sync-version.sh executable
        run: chmod +x ./sync-version.sh
      - name: Sync version
        run: ./sync-version.sh
      - name: Build
        run: npm run build
      - name: npm publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/lunaui-angular
