name: Release story book

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  avoid_redundancy:
    name: avoid redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs-on
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  lint:
    name: lint project
    needs: avoid_redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Lint
        run: npm run lint
  test:
    name: test project
    needs: avoid_redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Test
        run: npm run test
  build_storybook:
    needs:
      - lint
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Build story book
        run: npm run build-storybook

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: storybook-static
  publish:
    needs:
      - build_storybook
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: storybook-static  # Ensure this matches the publish_dir for GitHub Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: storybook-static
          clean: true
