# name: Update Library Release

# on:
#   workflow_dispatch:

# jobs:
#   release:
#     name: Release
#     permissions:
#       contents: write #Allows to publish a GH release
#       issues: write #Allows to comment on released issues
#       pull-requests: write #Allows to comment on released PRs
#       id-token: write # enable use of OIDC for npm provenance
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Node.js 20
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Install dependencies
#         run: npm ci
#       - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
#         run: npm audit signatures
#       - name: Build
#         run: npm run build
#       - name: Exec semantic-release
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           GITHUB_TOKEN: ${{ github.token }}
#         run: npx semantic-release
